var categoriesConstants = {
  RECEIVE_CATEGORIES: "RECEIVE_CATEGORIES",
  ADD_CATEGORY: "ADD_CATEGORY",
  RECEIVE_CATEGORY: "RECEIVE_CATEGORY",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY"
};

module.exports = categoriesConstants;
